version: '2'
services:
  caddy:
    image: caddy
    container_name: caddy
    volumes:
      - '/opt/caddy:/data'
      - '/opt/caddy/Caddyfile:/etc/caddy/Caddyfile'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - caddy
    restart: always
  3proxy:
    image: grffio/3proxy
    container_name: 3proxy
    environment:
      - PROXY_SECRET=user1:P@ssw0rd1,user2:P@ssw0rd2
    ports:
      - '1080:1080'
    networks:
      - 3proxy
    restart: always
  ocserv:
    image: grffio/ocserv
    container_name: ocserv
    environment:
      - OC_CERT=example.com.crt
      - OC_KEY=example.com.key
      - OC_SECRET=user1:P@ssw0rd1,user2:P@ssw0rd2
      - OC_MAXCL=4
      - OC_MAXSCL=1
    volumes:
      - '/opt/caddy/caddy/certificates/acme-v02.api.letsencrypt.org-directory/example.com:/etc/ocserv/cert:ro'
    ports:
      - '8443:443/tcp'
      - '8443:443/udp'
    networks:
      - ocserv
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - acmeshexec
  openvpn_tcp:
    image: grffio/openvpn
    container_name: openvpn_tcp
    environment:
      - OVPN_PROTO=tcp
      - OVPN_NETWORK=10.20.30.0
      - OVPN_MAXCL=4
      - OVPN_SERVERCN=example.com
    volumes:
      - '/opt/openvpn:/etc/openvpn/certs'
    ports:
      - '1194:1194/tcp'
    networks:
      - openvpn
    cap_add:
      - NET_ADMIN
    restart: always
  openvpn_udp:
    image: grffio/openvpn
    container_name: openvpn_udp
    environment:
      - OVPN_PROTO=udp
      - OVPN_NETWORK=10.20.30.0
      - OVPN_MAXCL=4
      - OVPN_SERVERCN=example.com
    volumes:
      - '/opt/openvpn:/etc/openvpn/certs:ro'
    ports:
      - '1194:1194/udp'
    networks:
      - openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - openvpn_tcp

  shadowsocks:
    image: grffio/shadowsocks
    container_name: shadowsocks
    volumes:
      - '/opt/shadowsocks:/opt/shadowsocks'
    networks:
      - shadowsocks
    restart: always
  cloak:
    image: grffio/cloak
    container_name: cloak
    environment:
      - CK_PROXYBOOK_SHADOWSOCKS=tcp://shadowsocks:8388
      - CK_BINDADDR=0.0.0.0:9443
    volumes:
      - '/opt/cloak:/opt/cloak'
    ports:
      - '9443:9443'
    networks:
      - shadowsocks
    restart: always
    depends_on:
      - shadowsocks
networks:
  caddy:
  3proxy:
  ocserv:
  openvpn:
  shadowsocks:
